;Afevis's Custom Lifebars
;All values have a max of 15 characters simply due to the nameplate not expanding further.
[Player]
player_o2=O2
player_grip=GRIP

player_tanker=LIFE
player_plant=LIFE

player_snake_tales_snake=LIFE
player_snake_tales_mgs1_snake=LIFE
player_snake_tales_pliskin=LIFE

player_vr_raiden=LIFE
player_vr_ninja_raiden=LIFE
player_vr_naked_raiden=LIFE

player_vr_snake=LIFE
player_vr_pliskin=LIFE
player_vr_tuxedo_snake=LIFE
player_vr_mgs1_snake=LIFE

[Bosses]
olga=OLGA
fatman=FATMAN
fortune=FORTUNE
harrier=HARRIER
vamp=VAMP
vamp_o2=VAMP O2
;ray's normally are called RAY-RANDOM_LETTERS. This will change the RAY part.
;10 characters max
ray_prefix=RAY
solidus=SOLIDUS

[Allies]
emma=EMMA
emma_o2=EMMA O2
kasatka=KASATKA
snake=SNAKE
meryl=MERYL
prez=PREZ

[Special]
genola=Genola
gurlugon=Gurlugon
mech_genola=Mech Genola


[Update Notifications]  
; If set to true, MGSM2Fix will notify you when launching the game if a new MGSM2Fix update is available for download.
CheckForUpdates = true
; If you want console notification when starting the game if a MGSM2Fix update is available.
; Update notifications will still be printed to the log file when set to false.
ConsoleNotifications = true


[Config Version]
;Keep this at the bottom
Version = 1

